name: Build - Everything

on:
  workflow_call:
    inputs:
      matrix-file-name:
        description: 'Json File containing arbitrary strategy-matrix; MUST be inside repository ./github folder'
        required: true
        type: string
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
      testballoon-version:
        description: 'Override TestBalloon version (full version string)?'
        required: false
        default: ''
        type: string
      build-matrix-runner:
        description: 'Name of target runner to parse build matrix; defaults to ubuntu-latest'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  prepare-matrix:
    name: Prepare build matrix
    uses: a-sit-plus/internal-workflows/.github/workflows/prepare-matrix.yml@v2
    with:
      file-name: ${{ inputs.matrix-file-name }}
      runner: ${{ inputs.build-matrix-runner }}

  build-jar:
    name: Build JAR - ${{ matrix.module }}
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    uses: a-sit-plus/internal-workflows/.github/workflows/build-jar-matrix-entry.yml@v2
    with:
      module: ${{ matrix.module }}
      kotlin-version: ${{ inputs.kotlin-version }}
      testballoon-version: ${{ inputs.testballoon-version }}

  build-xc:
    name: Build XCFramework - ${{ matrix.module }}
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    uses: a-sit-plus/internal-workflows/.github/workflows/build-xc-matrix-entry.yml@v2
    with:
      module: ${{ matrix.module }}
      artifact-name: ${{ matrix.artifactName }}
      kotlin-version: ${{ inputs.kotlin-version }}
      testballoon-version: ${{ inputs.testballoon-version }}
