name: Build - JAR Matrix Entry

on:
  workflow_call:
    inputs:
      module:
        description: "Module path/name (used for artifact name and jar path)"
        required: true
        type: string
      kotlin-version:
        description: "Override Kotlin version?"
        required: false
        default: ""
        type: string
      testballoon-version:
        description: "Override TestBalloon version (full version string)?"
        required: false
        default: ""
        type: string

jobs:
  build:
    name: "Build JAR (ubuntu-latest) - ${{ inputs.module }}"
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      TESTBALLOON_VERSION_OVERRIDE: ${{ inputs.testballoon-version }}

    steps:
      - name: Common setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@feature/modularTests

      - name: Build jar
        run: ./gradlew assemble

      - name: Upload jar ${{ inputs.module }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.module }}
          path: ${{ inputs.module }}/build/libs/*.jar
          if-no-files-found: error
