name: Test - Matrix Entry

on:
  workflow_call:
    inputs:
      override-cache:
        description: 'Override Cache?'
        required: true
        type: boolean
      os:
        description: 'GitHub Actions runner label to execute this test job on
          (e.g. ubuntu-latest, macos-latest, windows-latest).'
        required: true
        type: string
      name:
        description: 'Logical name of the matrix entry, used for display and reporting
          (for example: jvm, native, android, ios)'
        required: true
        type: string
      testCommand:
        description: 'Gradle command-line arguments specifying which tests to run'
        required: true
        type: string
      enable-kvm:
        description: 'Enable KVM for Android emulator tests'
        required: false
        default: false
        type: boolean
      setup-xcode:
        description: 'set xcode version'
        required: false
        default: false
        type: boolean
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
      testballoon-version:
        description: 'Override TestBalloon version (full version string)?'
        required: false
        default: ''
        type: string
      report-path:
        description: Glob for test result XML files
        type: string
        required: false
        default: "**/build/test-results/**/TEST*.xml,**/build/outputs/androidTest-results/managedDevice/**/TEST*.xml"
      metrics-path:
        description: Glob for metrics JSON files
        required: false
        type: string
        default: "metrics/*.json"

jobs:
  test:
    name: Test - ${{ inputs.name }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    timeout-minutes: 300

    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      TESTBALLOON_VERSION_OVERRIDE: ${{ inputs.testballoon-version }}

    steps:
      - name: Common setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@v2
        with:
          override-cache: ${{ inputs.override-cache }}
          enable-kvm: ${{ inputs.enable-kvm }}
          setup-xcode: ${{ inputs.setup-xcode }}

      - name: Run tests
        shell: 'bash'
        run: |
          export GRADLE_OPTS="-Dkotlin.build.report.json.directory=$PWD/metrics"
          ${{ inputs.testCommand }}

      - name: Reporting
        if: ${{ !cancelled() }}
        uses: a-sit-plus/internal-workflows/.github/actions/common-reporting@v2
        with:
          report-name: ${{ github.workflow }}
          matrix-identifier: ${{ runner.os }}-${{ inputs.name }}-${{ runner.arch }}
          report-path: ${{ inputs.report-path  }}
          metrics-path: ${{ inputs.metrics-path  }}
